FROM python:latest

WORKDIR /frontend/

COPY ./workstation-frontend/requirements.txt .

RUN pip install -r requirements.txt

COPY ./workstation-frontend/app .

EXPOSE 3000

# ENV APP_NAME 'workstation-frontend'
# ENV FLASK_ENV 'development'
# ENV FLASK_RUN_PORT 3000
# ENV FLASK_DEBUG True
# ENV HOST_BACKEND_URL 'http://192.168.1.40:5000'
# ENV APP_SECRET_KEY 'very secret key2'
ENV PYTHONPATH '${PYTHONPATH}:/frontend/'

CMD flask run --host=0.0.0.0 